# Generated by Django 4.2.1 on 2023-05-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
